name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build App
      run: xcodebuild -project "vas3k-club-ios.xcodeproj" -scheme "vas3k-club-ios" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO

